---
title: "Density Estimation"
author: "Gian Mario Sangiovanni - Daniele Ventura"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,             
  eval = TRUE,             
  warning = FALSE,        
  message = FALSE,         
  results = 'hide',        
  fig.align = 'center'     
)

setwd("C:/Users/gmsan/Dropbox/Object Detection")
expanded_x = c(658069.4, 658180.4)
expanded_y = c(4691988, 4692094)
#install.packages("sf")
#install.packages("tmap")
```

## Required Packages


```{r results}
library(sf)
library(SpatialKDE)
library(sp)
library(sf)
library(dplyr)
library(tmap)
library(raster)
library(adehabitatHR)
library(terra)
library(ggplot2)
library(gridExtra)
library(patchwork)
library(spatstat)
library(gdalraster)
library(readxl)
library(dplyr)
library(viridis)
library(png)
library(leaflet)

# Set coordinate reference system
epsg_code = 4326 # fix the epsg_code
crs_wkt = st_crs(epsg_code)$wkt
crs_proj = st_crs(epsg_code)$proj4string
```

## Data Import


```{r pressure}
# Import manual count and model detection data for different time periods
# April data
shape_sf_obs_4 = read_sf(dsn = paste(getwd(), sep ="", "/Dati/Manual Count/13-4-22_manual_count.shp"))
shape_sf_est_4 = read_sf(dsn = paste(getwd(), sep = "", "/Dati/Modello 200 Null no tiles/13-04-22_Conf_0.47-IoU_0.5.shp"))

# February data
shape_sf_obs_2 = read_sf(dsn = paste(getwd(), sep ="", "/Dati/Manual Count/20-2-22_manual_count.shp"))
shape_sf_est_2 = read_sf(dsn = paste(getwd(), sep = "", "/Dati/Modello 200 Null no tiles/20-02-22_Conf_0.47-IoU_0.5.shp"))

# June data
shape_sf_obs_6 = read_sf(dsn = paste(getwd(), sep ="", "/Dati/Manual Count/20-6-22_manual_count.shp"))
shape_sf_est_6 = read_sf(dsn = paste(getwd(), sep = "", "/Dati/Modello 200 Null no tiles/20-06-22_Conf_0.47-IoU_0.5.shp"))

# August data
shape_sf_obs_8 = read_sf(dsn = paste(getwd(), sep ="", "/Dati/Manual Count/24-8-22_manual_count.shp"))
shape_sf_est_8 = read_sf(dsn = paste(getwd(), sep = "", "/Dati/Modello 200 Null no tiles/24-08-22_Conf_0.47-IoU_0.5.shp"))

# October data
shape_sf_obs_10 = read_sf(dsn = paste(getwd(), sep ="", "/Dati/Manual Count/20-10-22_manual_count.shp"))
shape_sf_est_10 = read_sf(dsn = paste(getwd(), sep = "", "/Dati/Modello 200 Null no tiles/20-10-22_Conf_0.47-IoU_0.5.shp"))
```

```{r, echo=FALSE}


generate_seasonal_plots <- function(shape_sf_obs, shape_sf_est, season_title) {
  shape_utm_obs <- st_transform(shape_sf_obs, crs = 4326)
  shape_utm_est <- st_transform(shape_sf_est, crs = 4326)
  coord_obs <- st_coordinates(st_centroid(shape_sf_obs))
  coord_est <- st_coordinates(st_centroid(shape_sf_est))
  
  coord_est_df <- as.data.frame(coord_est)
  coord_obs_df <- as.data.frame(coord_obs)
  
  colnames(coord_obs_df) <- c("X", "Y")
  colnames(coord_est_df) <- c("X", "Y")
  
  coord_obs_df$category <- "observed"
  coord_est_df$category <- "estimated"
  
  combined <- rbind(coord_obs_df, coord_est_df)
  colnames(combined) <- c("X", "Y", "Type")
  
  p_obs <- ggplot(data = coord_obs_df, aes(X, Y)) +
    geom_density2d() +
    geom_point(alpha = 0.4, color = "darkgreen") +
    coord_fixed() +
    labs(title = paste("Observed", season_title),
         x = "Longitude", y = "Latitude") +
    theme_minimal()
  
  p_est <- ggplot(data = coord_est_df, aes(X, Y)) +
    geom_density2d() +
    geom_point(alpha = 0.4, color = "darkblue") +
    coord_fixed() +
    labs(title = paste("Estimated", season_title),
         x = "Longitude", y = "Latitude") +
    theme_minimal()
  

  
  # Return all plots as a list
  return(list(p_obs = p_obs, p_est = p_est))
}




```


```{r, echo=FALSE, warning=FALSE}


april_plots = generate_seasonal_plots(shape_sf_obs_4, shape_sf_est_4, "13-04-2022")
february_plots = generate_seasonal_plots(shape_sf_obs_2, shape_sf_est_2, "20-02-2022")
june_plots = generate_seasonal_plots(shape_sf_obs_6, shape_sf_est_6, "20-06-2022")
august_plots = generate_seasonal_plots(shape_sf_obs_8, shape_sf_est_8, "24-08-2022")
october_plots = generate_seasonal_plots(shape_sf_obs_10, shape_sf_est_10, "20-10-2022")

february_plots$p_obs + february_plots$p_est

april_plots$p_obs + april_plots$p_est

june_plots$p_obs + june_plots$p_est

august_plots$p_obs + august_plots$p_est

october_plots$p_obs + october_plots$p_est

# to merge them
#combined_all = wrap_plots(
#  february_plots$p_obs + february_plots$p_est, april_plots$p_obs + april_plots$p_est,
#  june_plots$p_obs + june_plots$p_est, august_plots$p_obs + august_plots$p_est, october_plots$p_obs + october_plots$p_est,
#  ncol = 2, 
#  nrow = 3, 
#  widths = c(1.3, 1.3),  
#  heights = c(1.1, 1.1, 1.1)
#) & 
#  theme(plot.margin = unit(c(0.2, 0.2, 0.2, 0.2), "cm")) 

#combined_all



```


## Misdetection per habitat 

```{r FP, echo=FALSE}
load("FP.RData")
df[df$habitat == "POSIDONIA_TRANSPLANTED", 2] = "POSIDONIA TRANSPLANTED"
df[df$habitat == "DEAD__MATTE__WITH_SAND", 2] = "DEAD MATTE WITH SAND"
df[df$habitat == "POSIDONIA_OCEANICA", 2] = "POSIDONIA OCEANICA"
df[df$habitat == "HARD_BOTTOMS_WITH_PHOTOPHILIC_ALGAE", 2] = "HARD BOTTOMS WITH PHOTOPHILIC ALGAE"
df[df$habitat == "SANDY_BOTTOMS", 2] = "SANDY BOTTOMS"
```


```{r FP2}
ggplot(df, aes(x = habitat, y = Proporzioni, fill = habitat)) +
  geom_bar(stat = "identity", color = "black") + 
  geom_text(aes(label = round(Proporzioni, 2)), vjust = -0.5, size = 5) + 
  facet_wrap(~ Campagna, 
             labeller = as_labeller(c("20-02-2022" = "February", 
                                      "13-04-2022" = "April",
                                      "20-06-2022" = "June", 
                                      "24-08-2022" = "August", 
                                      "20-10-2022" = "October"))) + 
  scale_fill_manual(values = c(
    "POSIDONIA TRANSPLANTED" = "green",
    "POSIDONIA OCEANICA" = "#257401",
    "HARD BOTTOMS WITH PHOTOPHILIC ALGAE" = "#73b2ff",
    "SANDY BOTTOMS" = "#feff01",
    "DEAD MATTE WITH SAND" = "brown"
  )) + 
  theme_minimal(base_size = 14) +
  ylim(c(0, 0.5)) +
  theme(axis.text.x = element_blank(),  
        axis.ticks.x = element_blank(), 
        legend.position = "bottom",  
        legend.background = element_rect(color = "black", fill = "white"),  
        panel.border = element_rect(color = "black", fill = NA),  
        strip.text = element_text(face = "bold")) +  
  labs(title = "",
       fill = "Habitat",
       y = "Frequency", 
       x = "") + 
  guides(fill = guide_legend(nrow = 1))

```

## Kernel Density Estimation

```{r KDE, warning=FALSE}
generate_density_map = function(shape_sf_obs, shape_sf_est, title_date) {

  
  coord_est = st_coordinates(st_centroid(shape_sf_est))
  coord_obs = st_coordinates(st_centroid(shape_sf_obs))
  
  bbox_est = st_bbox(shape_sf_est)
  bbox_obs = st_bbox(shape_sf_obs)
  
  window = owin(
    xrange = c(bbox_est["xmin"], bbox_est["xmax"]),
    yrange = c(bbox_est["ymin"], bbox_est["ymax"])
  )
  
  window_obs = owin(
    xrange = c(bbox_obs["xmin"], bbox_obs["xmax"]),
    yrange = c(bbox_obs["ymin"], bbox_obs["ymax"])
  )
  
  
  ppp_est = ppp(x = coord_est[,1], y = coord_est[,2], window = window)
  ppp_obs = ppp(x = coord_obs[,1], y = coord_obs[,2], window = window_obs)
  
  
  bandwidth = bw.ppl(ppp_obs)
  
  kde = density.ppp(ppp_est, sigma = bandwidth, kernel = "gaussian", at = "pixels", diggle = TRUE)
  kde_obs = density.ppp(ppp_obs, sigma = bandwidth, kernel = "gaussian", at = "pixels", diggle = TRUE)
  
  kde_raster = raster(kde)
  kde_raster_obs = raster(kde_obs)
  
  kde_df = as.data.frame(kde_raster, xy = TRUE)
  colnames(kde_df)[3] = "density"
  kde_df = kde_df[kde_df$density > 0.00012, ]
  
  kde_df_obs = as.data.frame(kde_raster_obs, xy = TRUE)
  colnames(kde_df_obs)[3] = "density"
  kde_df_obs = kde_df_obs[kde_df_obs$density > 0.00012, ]
  
  
  density_range = range(c(kde_df$density, kde_df_obs$density), na.rm = TRUE)
  
  x_range = range(kde_df$x, kde_df_obs$x, na.rm = TRUE)
  y_range = range(kde_df$y, kde_df_obs$y, na.rm = TRUE)
  

  
  map_est = ggplot() +
    geom_raster(data = kde_df, aes(x = x, y = y, fill = density)) +
    geom_sf(data = shape_sf_est, fill = NA, color = "black", alpha = 0.5) +
    scale_fill_viridis_c(name = "Density", limits = density_range) +
    theme_minimal() +
    coord_sf(xlim = expanded_x, ylim = expanded_y) +
    labs(title = paste("Detection Density Estimation", title_date),
         subtitle = paste("Gaussian Kernel", "Bandwidth:", round(bandwidth, 2)),
         x = "Longitude", y = "Latitude") +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
          axis.title = element_text(size = 14),
          axis.text = element_text(size = 9.5), 
          axis.text.x = element_text(angle = 45, hjust = 1))
  
  map_obs = ggplot() +
    geom_raster(data = kde_df_obs, aes(x = x, y = y, fill = density)) +
    geom_sf(data = shape_sf_obs, fill = NA, color = "black", alpha = 0.5) +
    scale_fill_viridis_c(name = "Density", limits = density_range, guide = "none") +  
    theme_minimal() +
    coord_sf(xlim = expanded_x, ylim = expanded_y) +
    labs(title = paste("Manual Count Density Estimation", title_date),
         subtitle = paste("Gaussian Kernel", "Bandwidth:", round(bandwidth, 2)),
         x = "Longitude", y = "Latitude") +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          panel.border = element_rect(colour = "black", fill = NA, linewidth = 1), 
          axis.title = element_text(size = 14),
          panel.spacing = unit(20,"mm"),
          axis.text = element_text(size = 9.5), 
          axis.text.x = element_text(angle = 45, hjust = 1))
  
  combined_plot = map_est + map_obs + plot_layout(ncol = 2, guides = "collect")
  
  return(combined_plot)
}


plot_4 = generate_density_map(shape_sf_obs_4, shape_sf_est_4, "April")
plot_4
plot_2 = generate_density_map(shape_sf_obs_2, shape_sf_est_2, "February")
plot_2
plot_6 = generate_density_map(shape_sf_obs_6, shape_sf_est_6, "June")
plot_6
plot_8 = generate_density_map(shape_sf_obs_8, shape_sf_est_8, "August")
plot_8
plot_10 = generate_density_map(shape_sf_obs_10, shape_sf_est_10, "October")
plot_10

plot_4 = plot_4 + theme(plot.margin = margin(0, 0, 0, 0))
plot_2 = plot_2 + theme(plot.margin = margin(0, 0, 0, 0))
plot_6 = plot_6 + theme(plot.margin = margin(0, 0, 0, 0))
plot_8 = plot_8 + theme(plot.margin = margin(0, 0, 0, 0))
plot_10 = plot_10 + theme(plot.margin = margin(0, 0, 0, 0))
# if you want to merge them 
#combined_all = wrap_plots(
#  plot_2, plot_4, 
#  plot_6, plot_8, 
#  plot_10, 
#  ncol = 2, 
#  nrow = 3, 
#  widths = c(1.3, 1.3),  
#  heights = c(1.1, 1.1, 1.1)
#) & 
#  theme(plot.margin = unit(c(0.2, 0.2, 0.2, 0.2), "cm"))  

#combined_all
```

